spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_URL}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
financial:
  api:
    base-url: ${FINANCIAL_BASE_URL}
    key: ${FINANCIAL_API_KEY}
    name: ?????
    default:
      account-type: ${FINANCIAL_DEFAULT_ACCOUNT_TYPE}
