spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    client:
      connect-timeout: 5000
      read-timeout: 5000

logging:
  level:
    root: INFO
    org.springframework.web: INFO

financial:
  api:
    base-url: ${FINANCIAL_BASE_URL}
    key: ${FINANCIAL_API_KEY}
    name: 쏠쏠한한끼
    default:
      account-type: ${FINANCIAL_DEFAULT_ACCOUNT_TYPE}
