spring:
  datasource:
    url: jdbc:postgresql://${PROD_POSTGRES_URL}:${POSTGRES_PORT}/${PROD_POSTGRES_DB}
    username: ${PROD_POSTGRES_USER}
    password: ${PROD_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

firebase:
  service:
    account:
      key:
        path: ${FIREBASE_SERVICE_ACCOUNT_PATH}

ddangyo:
  api:
    url: ${PROD_DDANGYO_API_URL}

payment:
  api:
    url: ${PROD_PAYMENT_API_URL}
  callback:
    url: ${PROD_PAYMENT_CALLBACK_URL}