# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: SolSolHanHanKki Deploy dev branch

on:
  push:
    branches: [ "develop" ]


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # set up java
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # gradle grant execution permission and build project
      - name: Setup Gradle
        run: |
          cd solsolhanhankki
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # login dockerhub
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # build Docker image
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.SOL_IMAGENAME }} ./solsolhanhankki

      # push docker image
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.SOL_IMAGENAME }}


  # run docker image
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOL_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SOL_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.SOL_IMAGENAME }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.SOL_IMAGENAME }}
            sudo docker stop ${{ secrets.SOL_IMAGENAME }} 2>/dev/null || true
            sudo docker rm ${{ secrets.SOL_IMAGENAME }}
            sudo docker-compose -f docker-compose.yml up -d {{ secrets.SOL_IMAGENAME }}
            sudo docker system prune -f
